node:
  version: 1
  type: 1

network:
  ip: 127.0.0.1
  port: 8333
  ping-interval: 120
  pong-timeout: 1200
  send-data-interval: 100
  get-addr-interval: 300
  max-number-of-connections: 10
  
miner:
  enabled: true
  public-key: 03f0d37776bd2b5f887d975888d6c8f6a1f1a1c7c7dfcd9926983db2960fd58d6a

government:
  public-key: 0328388180b9bb0eabf382cfdf86551d3744b694a70f4c26a1e52e6d120ec19570

ui:
  enabled: true

database:
  file: "databases/blockchain-test.db"

voters:
  file: "voters/voters.json"