name: Go Test Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.4'
      
      - name: Install GCC for CGO
        run: sudo apt-get update && sudo apt-get install -y gcc

      - name: Install Dependencies
        run: go mod tidy

      - name: Run Tests
        run: CGO_ENABLED=1 go test -count=1 -timeout=10m ./tests/... -v
